// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using solicitudMovimientosPcs.Data;

#nullable disable

namespace solicitudMovimientosPcs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251126221842_AddStageAccess")]
    partial class AddStageAccess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("solicitudMovimientosPcs.Models.Catalogs.PcMovimientosClase", b =>
                {
                    b.Property<string>("ClassCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CLASS_CODE");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ClassCode");

                    b.ToTable("PC_MOVIMIENTOS_CLASES", (string)null);
                });

            modelBuilder.Entity("solicitudMovimientosPcs.Models.Catalogs.PcMovimientosCodMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CONTENT");

                    b.Property<string>("PrcId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PRC_ID");

                    b.Property<string>("RsnCd")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("RSN_CD");

                    b.HasKey("Id");

                    b.HasIndex("PrcId", "RsnCd");

                    b.ToTable("PC_MOVIMIENTOS_COD_MOVIMIENTOS", (string)null);
                });

            modelBuilder.Entity("solicitudMovimientosPcs.Models.Catalogs.PcMovimientosCodigo", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DESCRIPCION");

                    b.HasKey("Codigo");

                    b.HasIndex("Descripcion");

                    b.ToTable("PC_MOVIMIENTOS_CODIGO", (string)null);
                });

            modelBuilder.Entity("solicitudMovimientosPcs.Models.Catalogs.PcMovimientosCodigoLinea", b =>
                {
                    b.Property<string>("AreaCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AREA_CODE");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AREA_NAME");

                    b.HasKey("AreaCode");

                    b.HasIndex("AreaName");

                    b.ToTable("PC_MOVIMIENTOS_CODIGO_LINEA", (string)null);
                });

            modelBuilder.Entity("solicitudMovimientosPcs.Models.Catalogs.PcMovimientosUbicacion", b =>
                {
                    b.Property<string>("Ubicacion")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("UBICACION");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("AREA");

                    b.HasKey("Ubicacion");

                    b.HasIndex("Area");

                    b.ToTable("PC_MOVIMIENTOS_UBICACION", (string)null);
                });

            modelBuilder.Entity("solicitudMovimientosPcs.Models.PcMovimientosAprobaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FinJpn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FINJPN");

                    b.Property<string>("FinJpnComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinJpnDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("FINJPN_DATE");

                    b.Property<string>("FinJpnStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FINJPN_STATUS");

                    b.Property<string>("FinMng")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FINMNG");

                    b.Property<string>("FinMngComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinMngDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("FINMNG_DATE");

                    b.Property<string>("FinMngStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FINMNG_STATUS");

                    b.Property<string>("Jpn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("JPN");

                    b.Property<string>("JpnComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("JpnDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("JPN_DATE");

                    b.Property<string>("JpnStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("JPN_STATUS");

                    b.Property<string>("Mc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MC");

                    b.Property<string>("McComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("McDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MC_DATE");

                    b.Property<string>("McStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MC_STATUS");

                    b.Property<string>("Mng")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MNG");

                    b.Property<string>("MngComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MngDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MNG_DATE");

                    b.Property<string>("MngStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MNG_STATUS");

                    b.Property<string>("PcJpn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PCJPN");

                    b.Property<string>("PcJpnComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PcJpnDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PCJPN_DATE");

                    b.Property<string>("PcJpnStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PCJPN_STATUS");

                    b.Property<string>("PcMng")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PCMNG");

                    b.Property<string>("PcMngComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PcMngDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PCMNG_DATE");

                    b.Property<string>("PcMngStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PCMNG_STATUS");

                    b.Property<string>("Pl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PL");

                    b.Property<string>("PlComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PL_DATE");

                    b.Property<string>("PlStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PL_STATUS");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("REQUEST_ID");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("PC_MOVIMIENTOS_APROBACIONES", (string)null);
                });

            modelBuilder.Entity("solicitudMovimientosPcs.Models.PcMovimientosItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CantidadA")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CANTIDAD_A");

                    b.Property<decimal?>("CantidadD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CANTIDAD_D");

                    b.Property<string>("Case")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CASE");

                    b.Property<string>("ClaseA")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CLASE_A");

                    b.Property<string>("ClaseD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CLASE_D");

                    b.Property<string>("CodMov")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("COD_MOV");

                    b.Property<decimal?>("CostoU")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("COSTO_U");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<decimal?>("Diferencia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DIFERENCIA");

                    b.Property<string>("EstatusA")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ESTATUS_A");

                    b.Property<string>("EstatusD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ESTATUS_D");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("ID_SOLICITUD");

                    b.Property<string>("Moneda")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("MONEDA");

                    b.Property<string>("NumParte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NUM_PARTE");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("NUMERO");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TOTAL");

                    b.Property<string>("UbicacionA")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UBICACION_A");

                    b.Property<string>("UbicacionD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UBICACION_D");

                    b.HasKey("Id");

                    b.HasIndex("IdSolicitud");

                    b.ToTable("PC_MOVIMIENTOS_ITEMS", (string)null);
                });

            modelBuilder.Entity("solicitudMovimientosPcs.Models.PcMovimientosRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("COMENTARIOS");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DEPARTAMENTO");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("FECHA");

                    b.Property<string>("Linea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LINEA");

                    b.Property<string>("PcDocumentoPath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("PC_DOC_PATH");

                    b.Property<DateTime?>("PcFinalDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PC_FINAL_DATE");

                    b.Property<string>("PcFinalizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PC_FINALIZADO_POR");

                    b.Property<string>("PcFolio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PC_FOLIO");

                    b.Property<string>("PcTipoMovimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcTiposMovimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("REQUEST_STATUS");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SOLICITANTE");

                    b.Property<string>("Urgencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("URGENCIA");

                    b.HasKey("Id");

                    b.ToTable("PC_MOVIMIENTOS_REQUEST", (string)null);
                });

            modelBuilder.Entity("solicitudMovimientosPcs.Models.Security.StageAccessEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Stage", "DisplayName")
                        .IsUnique();

                    b.ToTable("PC_STAGE_ACCESS");
                });

            modelBuilder.Entity("solicitudMovimientosPcs.Models.PcMovimientosAprobaciones", b =>
                {
                    b.HasOne("solicitudMovimientosPcs.Models.PcMovimientosRequest", "Solicitud")
                        .WithOne("Aprobaciones")
                        .HasForeignKey("solicitudMovimientosPcs.Models.PcMovimientosAprobaciones", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("solicitudMovimientosPcs.Models.PcMovimientosItem", b =>
                {
                    b.HasOne("solicitudMovimientosPcs.Models.PcMovimientosRequest", "Solicitud")
                        .WithMany("Items")
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("solicitudMovimientosPcs.Models.PcMovimientosRequest", b =>
                {
                    b.Navigation("Aprobaciones");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
